export const carData = [
    {
        Marke: "BMW",
        Modell: "M8 Gran Coupé Competition",
        PS: "625",
        Baujahr: "2021",
        Kraftstoff: "Benzin",
        Getriebe: "Automatik",
        Hubraum: "4395",
        VMax: "305",
        "1-100": "3,1",
        Kaution: "1000",
        Selbstbeteiligung: "2500",
        Preis8hMoDo: "190",
        Preis8hFrSo: "230",
        PreisTagMoDo: "360",
        PreisTagFrSo: "390",
        Gebucht: "18.07.2022-23.07.2022, 26.07.2022-28.07.2022",
        Bild: "/cars/bmw-m8-gc-c.jpeg",
        BoxPosition: "links",
        Beschreibung: "Maximale Fahrdynamik und Exklusivität. Viertüriger Luxuswagen voller adrenalingeladener Sportlichkeit.",
        Featured: "x",
        BaldVerfuegbar: "",
    },
    {
        Marke: "BMW",
        Modell: "M5",
        PS: "600",
        Baujahr: "2018",
        Kraftstoff: "Benzin",
        Getriebe: "Automatik",
        Hubraum: "4395",
        VMax: "305",
        "1-100": "3,4",
        Kaution: "1000",
        Selbstbeteiligung: "2500",
        Preis8hMoDo: "150",
        Preis8hFrSo: "190",
        PreisTagMoDo: "310",
        PreisTagFrSo: "340",
        Gebucht: "",
        Bild: "/cars/bmw-m5.jpeg",
        BoxPosition: "links",
        Beschreibung: "Verbindet auf überragende Weise M typische Sportlichkeit mit dem Komfort und der Eleganz einer Business-Limousine.",
        Featured: "",
        BaldVerfuegbar: "",
    },
    {
        Marke: "BMW",
        Modell: "X4 M Competition",
        PS: "510",
        Baujahr: "2021",
        Kraftstoff: "Benzin",
        Getriebe: "Automatik",
        Hubraum: "2993",
        VMax: "270",
        "1-100": "3,8",
        Kaution: "1000",
        Selbstbeteiligung: "2500",
        Preis8hMoDo: "150",
        Preis8hFrSo: "190",
        PreisTagMoDo: "270",
        PreisTagFrSo: "300",
        Gebucht: "",
        Bild: "/cars/bmw-x4-m-c.jpeg",
        BoxPosition: "rechts",
        Beschreibung: "Vereint das hohe Leistungspotenzial und die Exklusivität eines M Automobils mit dem progressiven Konzept eines BMW X4.",
        Featured: " ",
        BaldVerfuegbar: "x",
    },
];
